// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {

  // Add the new sidebar for Care Plans
  carePlansSidebar: [
    {
      type: 'autogenerated',
      dirName: 'care-plans', // Automatically generates sidebar from 'docs/care-plans'
    },
  ],

  openstaxAP2eSidebar: [
    {
      type: 'autogenerated',
      dirName: 'openstax-ap2e', // Automatically generates sidebar from 'docs/openstax-ap2e'
    },
  ],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
