// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  openstaxAP2eSidebar: [
    {
      type: 'autogenerated',
      dirName: 'anatomy-physiology/openstax-ap2e', // Automatically generates sidebar from 'docs/openstax-ap2e'
    },
  ],
  summariesSidebar: [
    {
      type: 'autogenerated',
      dirName: 'anatomy-physiology/summaries', // Automatically generates sidebar from 'docs/summaries'
    },
  ],
  flashcardsSidebar: [
    {
      type: 'autogenerated',
      dirName: 'anatomy-physiology/flashcards', // Automatically generates sidebar from 'docs/flashcards'
    },
  ],
  curriculumSidebar: [
    {
      type: 'autogenerated',
      dirName: 'anatomy-physiology/curriculum', // Automatically generates sidebar from 'docs/flashcards'
    },
  ],
  pathophysiologySidebar: [
    {
      type: 'autogenerated',
      dirName: 'pathophysiology', // Automatically generates sidebar from 'docs/flashcards'
    },
  ],
  disordersSidebar: [
    {
      type: 'autogenerated',
      dirName: 'disorders', // Automatically generates sidebar from 'docs/flashcards'
    },
  ],
  randomTopicsSidebar: [
    {
      type: 'autogenerated',
      dirName: 'random-topics', // Automatically generates sidebar from 'docs/flashcards'
    },
  ],
};

export default sidebars;
