// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // Explicitly define the items for the tutorial sidebar
  tutorialSidebar: [
    'intro', // Assuming 'docs/intro.md' is your Tutorial Intro
    {
      type: 'category',
      label: 'Tutorial Basics',
      link: {
        type: 'generated-index',
        title: 'Tutorial Basics',
        description: 'Learn the basics of Docusaurus!',
        slug: '/category/tutorial-basics'
      },
      items: [{type: 'autogenerated', dirName: 'tutorial-basics'}], // Autogenerate from 'docs/tutorial-basics' folder
    },
    {
      type: 'category',
      label: 'Tutorial Extras',
      link: {
        type: 'generated-index',
        title: 'Tutorial Extras',
        description: 'Learn about advanced Docusaurus features!',
        slug: '/category/tutorial-extras'
      },
      items: [{type: 'autogenerated', dirName: 'tutorial-extras'}], // Autogenerate from 'docs/tutorial-extras' folder
    },
    // NOTE: We are NOT including 'anatomy' here
  ],

  // Autogenerate the sidebar for the anatomy section from its directory
  anatomySidebar: [
    {
      type: 'autogenerated',
      dirName: 'anatomy-physiology', // Automatically generates sidebar from 'docs/anatomy'
    },
  ],

  // Add the new sidebar for Care Plans
  carePlansSidebar: [
    {
      type: 'autogenerated',
      dirName: 'care-plans', // Automatically generates sidebar from 'docs/care-plans'
    },
  ],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
